{
 "title": "Storage service",
 "description": "From https://github.com/minio/minio/blob/master/docs/metrics/prometheus/grafana/README.md",
 "tags": [
  "minio",
  "Storage",
  "S3"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(minio_version_info,instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(disk_storage_total,disk)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(minio_version_info,version)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket histogram",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bucket_objects_histogram{bucket=\"test\", object_size=\"BETWEEN_1024_B_AND_1_MB\"}",
     "legendFormat": "Between 1024B and 1MB"
    },
    {
     "expr": "bucket_objects_histogram{bucket=\"test\", object_size=\"BETWEEN_1_MB_AND_10_MB\"}",
     "legendFormat": "Between 1B and 10MB"
    },
    {
     "expr": "bucket_objects_histogram{bucket=\"test\", object_size=\"BETWEEN_10_MB_AND_64_MB\"}",
     "legendFormat": "Between 10MB and 64MB"
    },
    {
     "expr": "bucket_objects_histogram{bucket=\"test\", object_size=\"BETWEEN_64_MB_AND_128_MB\"}",
     "legendFormat": "Between 64MB and 128MB"
    },
    {
     "expr": "bucket_objects_histogram{bucket=\"test\", object_size=\"BETWEEN_128_MB_AND_512_MB\"}",
     "legendFormat": "Between 128MB and 512MB"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the MinIO Cluster",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Online disks",
   "type": "stat",
   "description": "Total online disks in MinIO Cluster",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minio_disks_total)",
     "legendFormat": "Total online disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Total Offline disks",
   "type": "stat",
   "description": "Total offline disks in MinIO Cluster",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minio_disks_offline)",
     "legendFormat": "Total offline disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Total Raw Capacity Used",
   "type": "stat",
   "description": "Total Raw Used Capacity in this MinIO Cluster",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(disk_storage_used)", "legendFormat": "Total Raw Capacity Used" }
   ]
  },
  {
   "title": "Total Raw Capacity Available",
   "type": "stat",
   "description": "Total Raw Capacity Available in this MinIO Cluster",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(disk_storage_available)", "legendFormat": "Total Raw Capacity Available" }
   ]
  },
  {
   "title": "Online Disks",
   "type": "graph",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_disks_total{instance=~\"$instance\"} - minio_disks_offline{instance=~\"$instance\"}",
     "legendFormat": "Online Disks {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Disk capacity used per MinIO Server",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_used{disk=~\"$disk\",instance=~\"$instance\"}",
     "legendFormat": "Used Capacity {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Storage per Bucket",
   "type": "bargauge",
   "description": "Storage capacity used per bucket in MinIO Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bucket_usage_size{instance=\"minio:9000\"}",
     "legendFormat": "Capacity used {{bucket}}"
    }
   ]
  },
  {
   "title": "Object Count per Bucket",
   "type": "bargauge",
   "description": "Count of objects per bucket in MinIO Cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bucket_objects_count{instance=\"minio:9000\"}",
     "legendFormat": "Object Count {{bucket}}"
    }
   ]
  },
  {
   "title": "S3 API Data Transfer",
   "type": "graph",
   "description": "Total number of s3 bytes received and sent per MinIO server instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_rx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "S3 Bytes Received {{instance}}"
    },
    {
     "expr": "rate(s3_tx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "S3 Bytes Sent {{instance}}"
    }
   ]
  },
  {
   "title": "Inter-node Data Transfer",
   "type": "graph",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(internode_rx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Internode Bytes Received {{instance}}"
    },
    {
     "expr": "rate(internode_tx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Internode Bytes Sent {{instance}}"
    }
   ]
  },
  {
   "title": "Active S3 Requests",
   "type": "graph",
   "description": "Total number of active s3 requests in current MinIO instance",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(s3_requests_current{instance=~\"$instance\"}[1m])  ",
     "legendFormat": "Total S3 Requests {{instance}} {{api}}"
    }
   ]
  }
 ]
}