---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  # - job_name: 'node'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['node:9100']

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # https://hub.docker.com/r/kpetrem/mqtt-exporter
  - job_name: mqtt-exporter
    static_configs:
      - targets: ["mqtt-exporter:9234"]
    # metric_relabel_configs:
    #   - source_labels: [sensor]
    #     regex: 'zigbee2mqtt_(.*)'
    #     replacement: '$1'
    #     target_label: sensor

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: minio-job
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
        - targets: ['minio:9000']